### ISSUE TITLE
Support for automating a #wcw post

### ISSUE THREAD

**Issue by josephfusco** [cyandterry/Like-My-GF#3]
@cyandterry 

Not sure if this is in the scope of the project, but I was just asked by my girlfriend :woman: why I haven't posted a #wcw (Woman Crush Wednesday) yet.

Would be fantastic to have a directory of images that the script will go through one by one each week and post with a #wcw hashtag and @mention of your significant other.

**Comment by josephfusco** [comment]
Ok it turns out that this cannot be done. [Instragram API](https://instagram.com/developer/endpoints/media/#get_media_popular) states this specifically :cry: 

> At this time, uploading via the API is not possible. We made a conscious choice not to add this for the following reasons:
> 1. Instagram is about your life on the go – we hope to encourage photos from within the app.
>    We want to fight spam & low quality photos. Once we allow uploading from other sources, it's harder to control what comes into the Instagram ecosystem.
> 2. All this being said, we're working on ways to ensure users have a consistent and high-quality experience on our platform.

**Comment by brunelli** [comment]
@josephfusco You may want to take a look at this: https://github.com/lukecyca/python-instagram-upload
